import 'package:flutter/material.dart';

class ListViewWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ListView(
      scrollDirection: Axis.vertical,
      children: [
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
        Text('Testing list view scrolling content'),
      ],
    );
  }
}
